spring:
  application:
    name: SistemaDeVaquinhaOnline-api

  datasource:
    url: jdbc:mysql://localhost:3306/vaquinha_db?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: admin
    driverClassName: com.mysql.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect